spring.application.name=universidad

server.port=8086

# ─────────────────────────────────────────────
# MySQL  →  estudiantes
# ─────────────────────────────────────────────
app.mysql.url=${MYSQL_URL:jdbc:mysql://localhost:3306/universidad_mysql?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
app.mysql.username=${MYSQL_USERNAME:spark_user}
app.mysql.password=${MYSQL_PASSWORD:Spark12345}
app.mysql.driver=com.mysql.cj.jdbc.Driver

# ─────────────────────────────────────────────
# SQL Server  →  carreras
# ─────────────────────────────────────────────
app.sqlserver.url=${SQLSERVER_URL:jdbc:sqlserver://localhost:1433;databaseName=universidad_sqlserver;encrypt=false;trustServerCertificate=true}
app.sqlserver.username=${SQLSERVER_USERNAME:sa}
app.sqlserver.password=${SQLSERVER_PASSWORD:Admin12345}
app.sqlserver.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ─────────────────────────────────────────────
# Neon (PostgreSQL cloud)  →  matriculas
# ─────────────────────────────────────────────
app.neon.url=${NEON_URL:jdbc:postgresql://ep-icy-credit-addwdv0n-pooler.c-2.us-east-1.aws.neon.tech/fabrizio_negron_10?sslmode=require}
app.neon.username=${NEON_USERNAME:neondb_owner}
app.neon.password=${NEON_PASSWORD:npg_YaNTA8PXIpU1}
app.neon.driver=org.postgresql.Driver
